// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Revendoo.Api.Context;

namespace Revendoo.Api.Migrations
{
    [DbContext(typeof(RevendooContext))]
    [Migration("20200413192346_ProductDescriptionLength")]
    partial class ProductDescriptionLength
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Revendo.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AmountStock");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6331de20-a020-4e4b-828b-5cb24627dab8"),
                            AmountStock = 10,
                            Description = "Batom",
                            Name = "Batom",
                            Price = 20.0
                        },
                        new
                        {
                            Id = new Guid("eb166e50-2234-40de-bcf6-5a17061880be"),
                            AmountStock = 1,
                            Description = "Rímel",
                            ExpirationDate = new DateTime(2020, 7, 22, 19, 23, 45, 856, DateTimeKind.Utc).AddTicks(9213),
                            Name = "Rímel",
                            Price = 12.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
