// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Revendoo.Api.Context;

namespace Revendoo.Api.Migrations
{
    [DbContext(typeof(RevendooContext))]
    partial class RevendooContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Revendo.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AmountStock");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("362d1041-b049-47f9-ad3d-4e6036b8d38f"),
                            AmountStock = 10,
                            Description = "Batom",
                            Name = "Batom",
                            Price = 20.0
                        },
                        new
                        {
                            Id = new Guid("b4cae03a-16b5-49b4-a85c-b709f638fdc2"),
                            AmountStock = 1,
                            Description = "Rímel",
                            ExpirationDate = new DateTime(2020, 7, 20, 20, 24, 17, 973, DateTimeKind.Utc).AddTicks(6652),
                            Name = "Rímel",
                            Price = 12.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
